### PR TITLE
Build search page

### PR DESCRIPTION
**Pull request by sam-shih**
Search page, not styled yet. Takes searched location and budget, passes to /photos/search

### CODE REVIEW

**Comment by JohnWebb4** [comment]
We didn't update index.test.js to match index.js, so Travis CI is failing. I fixed this in #17. If we PR my code first you should be fine. Otherwise you need to update index.text.js.

**Comment by JohnWebb4** [comment]
Thank you for adding exact path to the App.jsx page.

**Comment by JohnWebb4** [comment]
You need to re-base with upstream to pass Travis tests

**Comment by sam-shih** [comment]
Review Page and basic functionality built out as well.

**Pull request merged**
